### ISSUE TITLE
Unable to enable systemd service

### ISSUE THREAD

**Issue by kevin-roan** [flukejones/asusctl#10]
Distro: Arch Linux 
Asusctl version:  4.7.0-RC3

### Original Issue:
Sometimes after rebooting my system, the asusd service would automatically stop itself, and i had to manually start the service every time. When attempting to enable the service using `systemctl enable asusd`, an error was displayed indicating that the unit files lacked installation configuration in the [Install] section.

### Explanation:
The missing [Install] section prevented the automatic startup of the asusd service during system boot. 

### Solution:
Edit the systemd service file located at `/usr/lib/systemd/system/asusd.service`,
and add the following at the end of the file.

```
[Install]
WantedBy=multi-user.target
```

**Comment by flukejones** [comment]
A udev rule is used to enable the serice so that the daemon and service can be included in distros by default.
