### ISSUE TITLE
deckyloader plugin

### ISSUE THREAD

**Issue by fennectech** [flukejones/asusctl#13]
Id like to see a deckyloader plugin for this application.   for users running on things like the ROG ally the ability to manage things in the steam interface would be amazing

**Comment by flukejones** [comment]
I refuse to touch typescript, javascript, or python. Unfortunately dickyloader uses those so I won't be doing this. I am fairly sure others will be working on something similar.

**Comment by fennectech** [comment]
Fair enough.  All of those are pain incarnate.
