### ISSUE TITLE
Enable turning off flashing lights on Ally

### ISSUE THREAD

**Issue by fennectech** [flukejones/asusctl#14]
Currently windows is required to disable the flashing lights when charging on sleep mode on the ROG ally. Could you enable asusctl to do this?

**Comment by flukejones** [comment]
Yes it should be possible now. You will need a distro that carries my in-progress kernel patches also.

**Comment by fennectech** [comment]
Does nobara steam deck count?Sent from my iPadOn 3. Mar 2024, at 15:24, Luke Jones ***@***.***> wrote:﻿
Yes it should be possible now. You will need a distro that carries my in-progress kernel patches also.
