### ISSUE TITLE
MUX switch on non Asus laptop

### ISSUE THREAD

**Issue by MathisP75** [flukejones/asusctl#16]
Is the MUX switching feature using `asusctl bios -D 0` supposed to work on non Asus laptops? The README says features should work on all brands apart from the lights stuff. On my 2023 Lenovo Legion 7i Pro with an RTX 4090, running the above command does nothing, the process doesn't complete and all there is is a blinking terminal cursor on the next line. `supergfxctl` is installed and both the `asusd` service and the `supergfxd` service are running correctly.

**Comment by flukejones** [comment]
No, this is a tool for asus ROG laptops only. The readme says https://github.com/flukejones/asusctl?tab=readme-ov-file#supported-laptops

supergfx has some generic control that will work on other laptops.
