### ISSUE TITLE
Any plans to support Vivobook or other series?

### ISSUE THREAD

**Issue by szw0407** [flukejones/asusctl#17]
I tested the program on my Vivobook K6502VU, which also should have many of the functions including MUX switch and battery charging limit. However the program can't work fine here. I am asking whether it is planned to be supported by this program. Or, if it were to be supported, what work should be done? Thanks.

**Comment by flukejones** [comment]
I've submitted a kernel patch series including the Vivo MUX upstream to the kernel. You will see support eventually in 6.10 kernel. Good reason to be running a distro that does frequent mainline kernel updates.
