### ISSUE TITLE
No fan profile page 

### ISSUE THREAD

**Issue by ripplingsnake** [flukejones/asusctl#19]
I am on manjaro 6.7 I just installed asusctl latest is 5.08. The fan profile page is blank. There is small performance check box at the top but clicking it doesn’t do anything. The curve page is blank and there are no apply, reset to factory boxes at the bottom, the rest of the system settings are working fine

**Comment by flukejones** [comment]
Is this still an issue? Which distro and kernel?

**Comment by ripplingsnake** [comment]
No from 5.10 it is fixed thanks
