### ISSUE TITLE
Support for Asus Zephyrus G14 2024 (GA403UI)

### ISSUE THREAD

**Issue by jschoubben** [flukejones/asusctl#21]
I would like to help out bringing support for the 2024 G14 model (GA403UI).
I have little experience with Rust, but looking at the code, I think I'll manage.

My first main focus would be to add control for the newly added ledstrip on the back (which replaces the Animatrix if I'm not mistaken).

Looking at the rog-anime code, it seems like you communicate over USB using a specific Asus created protocol?
My hardware coding experiences are pretty rudimentary. Would it be possible to point me in some direction on how one could tackle this problem?
Maybe, the "Anime protocol" can even partly  be re-used or act as a starting point.

If anyone else has already been looking into this, please let me know :) 

Have a nice day!

**Comment by jschoubben** [comment]
I've managed to implement the following features for the Slash ledstrip:
    -  Enable / Disable
    - Set brightness 
      On a scale from [0-10] but it gets translated to [0-255]
    - Set interval 
      Timeout between the slash effect
    - Set mode
      There are 15 or so modes which you can choose from. I haven't looked into custom effects because my main focus was to simply turn it off)

I'll now try to integrate it cleanly in the existing solution and submit a PR.

Since this could take some time, if anyone's interested, just give me a nudge.

**Comment by jschoubben** [comment]
#23

**Comment by laukkw** [comment]
Hello, my device is a 2024 G14 GA403UV. I use linux-g14 with a kernel of 6.8.2. I have a problem with the sound. I would like to know if you have the same problem.

**Comment by jschoubben** [comment]
I do have the same issue, only the "tweeter"? is working if I understand correctly. So the bass and mid level speakers are not working in my setup.
Since I always use headphones, this is not really an issue, but there's an article on the asus-linux.org website about it: https://asus-linux.org/guides/cirrus-amps/

Did you also try to control the Slash ledstrip already? I found it annoying as hell since I use my laptop at the office :)

**Comment by laukkw** [comment]
my laptop has linux and windows. When I turn off the windows light strip, the linux light strip will also turn off.
I refer to the arch wiki for keyboard light settings and turned it off.
