### ISSUE TITLE
latest build fails on Ally 

### ISSUE THREAD

**Issue by ripplingsnake** [flukejones/asusctl#26]
Compiling rog_dbus v6.0.0-alpha2 (/home/marc/asusctl/rog-dbus)
   Compiling asusd-user v6.0.0-alpha2 (/home/marc/asusctl/asusd-user)
error[E0432]: unresolved imports `rog_aura::keyboard::LaptopOldAuraPower`, `rog_aura::keyboard::LaptopTufAuraPower`
  --> rog-control-center/src/types/aura_types.rs:49:42
   |
49 | use rog_aura::keyboard::{AuraPowerState, LaptopOldAuraPower, LaptopTufAuraPower};
   |                                          ^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `LaptopTufAuraPower` in `keyboard`
   |                                          |
   |                                          no `LaptopOldAuraPower` in `keyboard`
   |
help: a similar name exists in the module
   |
49 | use rog_aura::keyboard::{AuraPowerState, LaptopAuraPower, LaptopTufAuraPower};
   |                                          ~~~~~~~~~~~~~~~
help: a similar name exists in the module
   |
49 | use rog_aura::keyboard::{AuraPowerState, LaptopOldAuraPower, LaptopAuraPower};
   |                                                              ~~~~~~~~~~~~~~~

error[E0432]: unresolved import `rog_aura::usb::AuraPowerDev`
  --> rog-control-center/src/types/aura_types.rs:50:5
   |
50 | use rog_aura::usb::AuraPowerDev;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AuraPowerDev` in `usb`
   |
help: consider importing this struct through its public re-export instead
   |
50 | use crate::AuraPowerDev;
   |     ~~~~~~~~~~~~~~~~~~~

error[E0432]: unresolved import `rog_aura::usb::AuraPowerDev`
 --> rog-control-center/src/ui/setup_aura.rs:3:5
  |
3 | use rog_aura::usb::AuraPowerDev;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AuraPowerDev` in `usb`
  |
help: consider importing this struct through its public re-export instead
  |
3 | use crate::AuraPowerDev;

**Comment by flukejones** [comment]
Main is never stable, only release tags are.
