### ISSUE TITLE
asusd.service must be started manually on Zenbook

### ISSUE THREAD

**Issue by chrnin** [flukejones/asusctl#28]
Hello,

it looks like asusd service doesn't start by itself on my Asus Zenbook 3504… I fixed it locally by tweaking custom udev rules…

For the recorde, dmidecode says `Family: Zenbook`.
With the all informations I don't have on Zenbooks support, I'd add a naïve:
```
ENV{DMI_FAMILY}=="*Zenbook*", GOTO="asusd_start"
```

I can attest that asusd service works like a charm on my laptop, I use it daily since months, maybe other zenbooks have issues ?

For a detailed info, I attached my dmidecode output: [dmidecode.txt](https://github.com/flukejones/asusctl/files/14970072/dmidecode.txt)

**Comment by flukejones** [comment]
what does asusd actually provide for zenbooks?

**Comment by flukejones** [comment]
PR merged.
