### ISSUE TITLE
Gui errors

### ISSUE THREAD

**Issue by cebem1nt** [flukejones/asusctl#33]
Ive used this asuctl gui before but after update it doesn't run just. i can still change from terminal, but gui doesnt work. Ive tried to run with rog-controll-center but got an error:

rog-control-center
[ERROR rog_control_center::tray] Tray unable to be initialised: TrayError: Os(MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name is not activatable"), Msg { type: Error, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 20, body: Signature("s"), fds: [] }))
    	at /usr/src/debug/asusctl/cargo/registry/src/index.crates.io-6f17d22bba15001f/betrayer-0.2.0/src/platform/linux/mod.rs:120:9. Do you have a system tray enabled?
thread 'main' panicked at /usr/src/debug/asusctl/asusctl/target/release/build/rog-control-center-79c6bd8134572f85/out/main_window.rs:89584:49:
called `Result::unwrap()` on an `Err` value: Other("Error creating gbm surface: Function not implemented (os error 38)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    6080 IOT instruction (core dumped)  rog-control-center

**Comment by Ghanshyam-shaktawat** [comment]
Hello there, I am facing a similar issue but in my case the apps start but there is no system tray icon for Rog control center. It happened after I updated to the latest version today.

I am using arch Linux
asusctl version 6.0.6
Linux kernel - 6.6.30-2-lts
Laptop - Asus tuff A15

**Comment by Ghanshyam-shaktawat** [comment]
Update: I just reinstalled rog-control-center and it fixed my issue.  Now i am getting the system tray icon.

**Comment by flukejones** [comment]
Arch and custom setups are not supported (by me, I only support Fedora with Gnome, KDE, or Cosmic. It's just a matter of personal time and scope).

Most likely y'all are running something non standard.
