### ISSUE TITLE
Setting PL1 failed

### ISSUE THREAD

**Issue by snow-nene** [flukejones/asusctl#37]
![image](https://github.com/flukejones/asusctl/assets/113535139/e56d43fd-e709-4ea7-811f-7de98cc190f6)
When I try to set the PL1, it fails. And I find my long term power of cpu is limited to 45w while the tempature is not high far behind the 95 degree tempature wall.

(base) [clifford@archlinux ~]$ asusctl -v
Starting version 6.0.10
asusctl v6.0.10
![image](https://github.com/flukejones/asusctl/assets/113535139/35ef7382-6a01-48e5-8ac9-4cd7c873bb08)

**Comment by flukejones** [comment]
It actually does write fine. But the read-back fails due to requiring kernel patches (which I work on, and will submit upstream).

**Comment by flukejones** [comment]
You should use the G14 kernel from https://asus-linux.org/guides/arch-guide/
