### ISSUE TITLE
dGPU always active even in integrated mode

### ISSUE THREAD

**Issue by mantasjk** [flukejones/asusctl#4]
Hello, on M16 2022 machine (12700H, 3060) dGPU always stays active in hybrid, and even integrated mode. To set everything up I followed F36 workstation guide. Machine is running old 302 BIOS.

I attach asusd and superfxd logs, as suggested by krst:
[asusd_log.txt](https://github.com/flukejones/asusctl/files/8459753/asusd_log.txt)
[superfxd_log.txt](https://github.com/flukejones/asusctl/files/8459754/superfxd_log.txt)

**Comment by megawebmaster** [comment]
I have a very similar problem, but I have newest BIOS 306 version.

**Comment by flukejones** [comment]
Appologies for not seeing this. Github is terrible at notifications (I rely on gitlab and email).

I'd be willing to bet you need to use armoury crate to disable MUX/dedicated or something similar. dGPU should be auto.

**Comment by arumihsnek** [comment]
I have the same problem when I boot the mode is integrated but the dGPU is enabled, but when I do `supergfx -m integrated` gnome logout and when i log in the dGPU seems disabled.
I need to do that in each time I whant to disable de dGPU.

**Comment by flukejones** [comment]
Something else is rescanning the PCI bus after supergfxd.
