### ISSUE TITLE
G14 2023 AniMe Matrix device not recognized

### ISSUE THREAD

**Issue by refinedm5** [flukejones/asusctl#8]
I'm on Ubuntu 23.04 and v4.6.2 does not recognize the lid with error "org.freedesktop.DBUS.Error.UnkownObject: Unknown object '/org/asuslinux/Anime'"
![Screenshot from 2023-06-04 03-43-07](https://github.com/flukejones/asusctl/assets/15518830/24382c84-c528-4e36-b043-3dcf37086bb1)

**Comment by flukejones** [comment]
Lack of information, old issue, old version. Please try latest release.

**Comment by AManNeedsAMaid** [comment]
I get this same issue on version 5.0.8 on a G14 with board 'GA402RJ'. Not bothered with being unable to use the matrix display, but I'd prefer it.
