### ISSUE TITLE
asusctl-notify (systemctl --user enable asus-notify.service) : Failed to connect to bus: No medium found

### ISSUE THREAD

**Issue by tetoNidan** [flukejones/asusctl#9]
OS: Arch
Kernel: 6.3.5-arch1-2-g14
DE: Plasma 5.27.5
Package built with pacman following the Arch Setup Guide

Like the title says the notifications service fails to enable and or start. However from the rog-control-center the notifications work just fine but they disappear before you can read them. Almost instantly. I will set up an issue about the rof-control-center on gitlab probably tomorrow. 

Any info I can provide you that can help or if there is something I can do to test let me know.

Thanks for your work, this project is pretty awesome!

**Comment by flukejones** [comment]
asusctl-notify is old and deprecated.
